AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating a VPC and subnets

Parameters:
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: 192.168.0.0/16

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 192.168.0.0/24
      AvailabilityZone: us-east-1a

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 192.168.1.0//24
      AvailabilityZone: us-east-1b

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 192.168.2.0//24
      AvailabilityZone: us-east-1a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 192.168.3.0//24
      AvailabilityZone: us-east-1b

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref MyVPC
    ####
    ########3
    ############3
    ################
    ################33
